# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: build_stage
  displayName: MVN Build
  jobs:
   - job: maven_install
     pool: 
       vmImage: ubuntu-latest
     steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'install'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
     
- stage: Build_docker
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'vscbobba/rahulsacademy'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
